### ISSUE TITLE
Suggested inclusion of masks to extract data for Fish-MIP regional models

### ISSUE THREAD

**Issue by lidefi87** [ISI-MIP/isimip-files-api#3]
Hi there,

I work with the Fish-MIP group and we are working on creating a simple workflow to show modelers how they can extract ocean model outputs for their regions of interest so they can run their models. I was wondering if you would be interested in adding some masks with the boundaries of the Fish-MIP regions to the `isimip-client` library. This will make it easier for modelers to extract and download only the data they need to run their models.

We have masks available in three resolutions used by the ESMs, and we also have shapefiles if that is more convenient. 

I was thinking this could added as you already have an option to extract data by countries, which leads me to think that data extraction with boundaries more complex than a bounding box is possible for your library.

If this is something that you would be interested in incorporating to your library, let me know and I am happy to be involved as much as possible to make this happen.

**Comment by jochenklar** [comment]
Hi @lidefi87 , sorry for not responding earlier. We plan to add support for uploading shapefiles (and GEOJsons) to https://github.com/ISI-MIP/isimip-files-api later this year. The idea is that you can upload your own shapefile (through data.isimip.org or using `isimip-client`) and the mask is created on the server as part of the process.

We can also add a set of "official" Fish-MIP masks to the API (like the country masks now).

It would be nice if you could provide us with the shapefiles you mentioned. You are probably in contact with @thiasB already.

I will transfer the issue to https://github.com/ISI-MIP/isimip-files-api.

**Comment by lidefi87** [comment]
I somehow completely missed your response @jochenklar. I have a single shapefile covering all FishMIP regional projects. From memory, there were 2 or 3 regions overlapping, so if this is a problem, I can provide a single shapefile per region.

I have not heard from @thiasB yet, but let me what would be the best way to share these and I will get them to you.

**Comment by jochenklar** [comment]
Hi @lidefi87 , after some month we now have version 2 of the API online. It is now possible to upload a shapefile to extract regions. There is some documentation here https://github.com/ISI-MIP/isimip-files-api/blob/main/docs/operations.md#create-mask and an example notebook (with some extra steps) is available here: https://git.rwth-aachen.de/nfdi4earth/pilotsincubatorlab/incubator/climate-impact-data-extraction/-/blob/main/notebooks/2-mask-region-high-resolution.ipynb?ref_type=heads.

**Comment by lidefi87** [comment]
Hi @jochenklar, this works great, but I emailed you a question earlier today.
